apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  labels:
    app: webapp
spec:
  containers:
  - name: webapp
    image: webappacr.azurecr.io/webapp:latest
    ports:
    - containerPort: 8080
    securityContext:
      runAsUser: 1000
      runAsGroup: 3000
      fsGroup: 2000
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
    resources:
      limits:
        cpu: "1"
        memory: "512Mi"
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
